import auxiliaries
import binance

KLINTERVAL        = auxiliaries.KLINE_INTERVAL_ID_1m
KLINTERVAL_CLIENT = binance.Client.KLINE_INTERVAL_1MINUTE
KLINTERVAL_STREAM = "1m"
KLINTERVAL_S      = 60

NLINES_SMA     = 10
NLINES_WMA     = 10
NLINES_EMA     = 10
NLINES_PSAR    = 10
NLINES_BOL     = 10
NLINES_SWING   = 10
NLINES_VOL     = 10
NLINES_NNA     = 10
NLINES_MMACD   = 5*2
NLINES_DMIxADX = 10
NLINES_MFI     = 10
NLINES_TPD     = 10
NLINES_NES     = 10
NLINES_WOI     = 10

KLINDEX_OPENTIME         =  0
KLINDEX_CLOSETIME        =  1
KLINDEX_OPENPRICE        =  2
KLINDEX_HIGHPRICE        =  3
KLINDEX_LOWPRICE         =  4
KLINDEX_CLOSEPRICE       =  5
KLINDEX_NTRADES          =  6
KLINDEX_VOLBASE          =  7
KLINDEX_VOLQUOTE         =  8
KLINDEX_VOLBASETAKERBUY  =  9
KLINDEX_VOLQUOTETAKERBUY = 10
KLINDEX_CLOSED           = 11
KLINDEX_SOURCE           = 12

DEPTHINDEX_OPENTIME  = 0
DEPTHINDEX_CLOSETIME = 1
DEPTHINDEX_BIDS5     = 2
DEPTHINDEX_BIDS4     = 3 
DEPTHINDEX_BIDS3     = 4
DEPTHINDEX_BIDS2     = 5 
DEPTHINDEX_BIDS1     = 6 
DEPTHINDEX_BIDS0     = 7 
DEPTHINDEX_ASKS0     = 8 
DEPTHINDEX_ASKS1     = 9 
DEPTHINDEX_ASKS2     = 10 
DEPTHINDEX_ASKS3     = 11
DEPTHINDEX_ASKS4     = 12
DEPTHINDEX_ASKS5     = 13
DEPTHINDEX_CLOSED    = 14
DEPTHINDEX_SOURCE    = 15

ATINDEX_OPENTIME     = 0
ATINDEX_CLOSETIME    = 1
ATINDEX_QUANTITYBUY  = 2
ATINDEX_QUANTITYSELL = 3
ATINDEX_NTRADESBUY   = 4
ATINDEX_NTRADESSELL  = 5
ATINDEX_NOTIONALBUY  = 6
ATINDEX_NOTIONALSELL = 7
ATINDEX_CLOSED       = 8
ATINDEX_SOURCE       = 9

DEPTHBINS = {DEPTHINDEX_BIDS5: (-5.0, -4.0),
             DEPTHINDEX_BIDS4: (-4.0, -3.0),
             DEPTHINDEX_BIDS3: (-3.0, -2.0),
             DEPTHINDEX_BIDS2: (-2.0, -1.0),
             DEPTHINDEX_BIDS1: (-1.0, -0.2),
             DEPTHINDEX_BIDS0: (-0.2,  0.0),
             DEPTHINDEX_ASKS0: ( 0.0,  0.2),
             DEPTHINDEX_ASKS1: ( 0.2,  1.0),
             DEPTHINDEX_ASKS2: ( 1.0,  2.0),
             DEPTHINDEX_ASKS3: ( 2.0,  3.0),
             DEPTHINDEX_ASKS4: ( 3.0,  4.0),
             DEPTHINDEX_ASKS5: ( 4.0,  5.0)}
