import auxiliaries
import binance

KLINTERVAL        = auxiliaries.KLINE_INTERVAL_ID_1m
KLINTERVAL_CLIENT = binance.Client.KLINE_INTERVAL_1MINUTE
KLINTERVAL_STREAM = "1m"
KLINTERVAL_S      = 60

NLINES_SMA     = 10
NLINES_WMA     = 10
NLINES_EMA     = 10
NLINES_PSAR    = 5
NLINES_BOL     = 10
NLINES_SWING   = 5
NLINES_VOL     = 5
NLINES_NNA     = 5
NLINES_MMACD   = 5*2
NLINES_DMIxADX = 10
NLINES_MFI     = 10
NLINES_TPD     = 5
NLINES_NES     = 3
NLINES_WOI     = 3
